name: PaintBattle
version: '${project.version}'
main: snowsan0113.paintbattle.Main
api-version: '1.20'

commands:
  paintbattle_start:
    description: ゲームを開始するコマンド
    permission: snowsan0113.paint_battle.command.game_start
  paintbattle_team:
    description: チームに関するコマンド
    permission: snowsan0113.paint_battle.command.team
  paintbattle_weapon:
    description: 武器に関するコマンド
    permission: snowsan0113.paint_battle.command.weapon
  paintbattle_map:
    description: マップに関するコマンド
    permission: snowsan0113.paint_battle.command.map
